from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class LiveTickerMessage(BaseModel):
    timestamp: str = Field(..., description="Simulated timestamp string (e.g., '21:14')")
    agent_profile: str = Field(..., description="'female_commuter' or 'qingqi_driver'")
    log_level: str = Field(..., description="'CRITICAL', 'WARNING', or 'INFO'")
    message: str = Field(..., description="The localized, raw stream-of-consciousness flag from the agent.")

class BlueprintRevision(BaseModel):
    original_element: str = Field(..., description="The infrastructure element proposed by the official.")
    failure_mode_detected: str = Field(..., description="Why it fails according to our multi-agent matrix.")
    amended_design_fix: str = Field(..., description="The concrete generative architectural correction.")

class FeasibilityScores(BaseModel):
    social_impact_score: float
    economic_viability_score: float
    political_feasibility_score: float

class SimulationRunRequest(BaseModel):
    project_id: str = Field(..., example="saddar-lahore-cleanup")
    agent_count: int = Field(default=50, ge=10, le=500)
    enable_informal_nodes: bool = Field(default=True, description="Toggle tracking for Qingqi/Rickshaw congregations.")

class SimulationStateResponse(BaseModel):
    project_id: str
    status: str
    scores: FeasibilityScores
    summary_verdict: str = Field(..., description="The final executive text block generated by the arbitrator.")
    live_debate_ticks: List[LiveTickerMessage] = Field(..., description="Data array powering the Live-Debate Ticker view.")
    blueprint_revisions: List[BlueprintRevision] = Field(..., description="Data array powering the Before/After Revision view.")
    spatial_telemetry: Dict[str, Any] = Field(..., description="GeoJSON FeatureCollection optimized with Friction Heatmap weights.")
